### ISSUE TITLE
the space between s,i,j letters in italic style need optimize

### ISSUE THREAD

**Issue by zhimoe** [MonoLisaFont/feedback#119]
just test on official website, the space in 'sam' and 'fij' looks strange
## Issue
<img width="399" alt="iShot2022-01-13 22 30 09" src="https://user-images.githubusercontent.com/24514012/149349726-821a63e5-5f31-4d69-a8a6-31ea52b15194.png">

**Comment by MarcusSterz** [comment]
Thanks for your feedback! All monospaced fonts have a great disadvantage compared to proportional typefaces: space cannot be distributed as evenly as needed due to the fixed width and one of the main design goals is to minimize the consequences. Sometimes certain combinations such as the ones you posted look awkward and there will always be some more. Unfortunately there is no way to prevent this entirely no matter how hard we try. 
Still thx for heads up!
