### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by fxn** [MonoLisaFont/feedback#147]
Hi!

The website shows `1.808` in the download dropdown

<img width="437" alt="Screen Shot 2022-04-25 at 11 03 42" src="https://user-images.githubusercontent.com/3387/165057075-49c96217-aebe-401d-aa8f-aeac37df016a.png">

but inspecting in Font Book says `1.807`:

<img width="473" alt="Screen Shot 2022-04-25 at 11 04 24" src="https://user-images.githubusercontent.com/3387/165057194-a93a00ac-6bea-480f-bbfc-a6b4222baefd.png">

I deleted and installed again just in case, still `1.807`.

**Comment by bebraw** [comment]
For reference, here's what I get through our internal GitHub API (either individual file or from zip):

<img width="272" alt="Screen Shot 2022-04-27 at 9 46 35" src="https://user-images.githubusercontent.com/166921/165457918-3b742c40-38fd-4a53-b677-5a0d7d642ccd.png">

Maybe there's something in between catching the wrong version as there's some API bit on top of the GitHub layer.

@fxn Note that there's no functional difference between 1.807 and 1.808 as we pushed 1.808 because the version metadata was incorrect in ttf at 1.807 so in technical terms it's the same font. Thanks for reporting, though, as this might affect the next release.

**Comment by okonet** [comment]
What is the Finder.app saying when you download the font but before you install it? I'm getting the right version so could it be the Fonts.app?

**Comment by fxn** [comment]
Interesting! Inspecting in Finder says 1.808, and now FontBook says 1.808.

Since the bug report I closed FontBook and there has also been a reboot. Smells like caching.

All seems good then as far as the font metadata is concerned. Closing!
