### ISSUE TITLE
[Bug]: Turn ligatures off also removes script variant

### ISSUE THREAD

**Issue by danulqua** [MonoLisaFont/feedback#182]
### Edition

Plus

### What version are you using?

2.003

### What type of weights are you using?

Static (customized)

### Operating system

macOS Ventura 13.1

### Display resolution

Not related

### What happened?

I don't like ligatures, so I've turned them off. But in this case Script variant doesn't work. I wrote everything what the FAQ says.
![CleanShot 2022-12-23 at 16 29 00@2x](https://user-images.githubusercontent.com/38916225/209360608-412c4aa0-5853-446c-8ec3-98a9a58d6d60.jpg)

**Comment by bebraw** [comment]
Note that it's preferable to the non-customized version (first download) with VS Code as customization doesn't provide any value there. The feature exists for other editors.

Is there a specific reason why you want to use a customized version with it?

It's still a bug, so please don't close.

**Comment by danulqua** [comment]
@bebraw the problem is that if I download the customized version where I turn off ligatures and turn on script - even in the font preview script doesn't show up (but it does if the ligatures were turned on).

![CleanShot 2022-12-23 at 19 02 34@2x](https://user-images.githubusercontent.com/38916225/209373648-58600dd5-3517-4143-9f66-97896c020a44.jpg)

**Comment by bebraw** [comment]
@danulqua Are you saying even the non-customized version doesn't work for you in VS Code?

**Comment by danulqua** [comment]
@bebraw I mean that (see screenshot). I turn on script, and turn off ligatures, and remove `editor.fontLigatures` from the `settings.json`. It still doesn't work as expected. Also, script doesn't show up in the font preview in the app `Font book`.

![CleanShot 2022-12-23 at 19 08 46@2x](https://user-images.githubusercontent.com/38916225/209374306-5823328a-9405-45fb-aaea-c52c073afd03.jpg)

**Comment by bebraw** [comment]
@danulqua That's not what I meant. It's best to use the first download with VS Code and then use VS Code settings to enable the features like you did. Did you try this?

Please don't use the customize tool with VS Code as it breaks its configuration.

**Comment by danulqua** [comment]
@bebraw oh, got it, it works with all default settings!
But seems like if other software doesn't have such availability to turn on/off certain font features, I have to download another font variant?
I just wanted to get rid of ligatures and use second script variant.

**Comment by bebraw** [comment]
@danulqua That's exactly why the customize feature exists. Since other editors don't provide good support for the features, we bypass that by allowing you to freeze the features you want to the font itself. You can give it a custom name then and then point to it since that's something you can change in other tools.

VS Code is the exception to this rule. Kitty terminal is another.

**Comment by okonet** [comment]
The way feature freezeing works now is it relies on `Liga` sind you can’t have it turned off and have customizations. The UI doesn’t reflect it yet and there might be a way to have both so it needs more research. But in general, if your editor supports open type features like toggling ligatures, you should always use it instead of our customization tool. 

We plan to improve the UI to make this less confusing in the future.

**Comment by danulqua** [comment]
Maybe, a tooltip near "No liga" with something like "customizations will not work" would be good, or if user chooses "no liga" - all customizations become disabled.
Anyways, thanks for the clarification!

**Comment by okonet** [comment]
Yes I’m planning to improve this soon. Sorry for the confusion.
