### ISSUE TITLE
[Bug]: ss10 should not shift the `>` and `<` vertically when applied

### ISSUE THREAD

**Issue by okonet** [MonoLisaFont/feedback#193]
### Edition

Plus

### What version are you using?

2.100

### What type of weights are you using?

Default (non-customized)

### Operating system

MacOS

### Program

VSCode

### What happened?

When `ss10` is applied, while typing `>=` the `>` jumps a few pixels. It's also visible on the website:

https://user-images.githubusercontent.com/11071/219093013-c97cb564-190f-4b51-8576-09f19e977078.mp4

Ideally, the `>` and `<` glyphs should remain the same to make the substation look more natural.

**Comment by MarcusSterz** [comment]
I think this transition never actually occurs visibly.
Please look at the different ‘Greater’ appearances. Total uniformity is hardly achievable anyway. 
The second sign has to be closely related to the first for obvious reasons (math symbols).
The third and fourth need to be uniform, since fourth is a variation of three.
The horizontal stem of second is closer to the > shape since it almost touches it but then spreads, which does not happen in third and fourth sign, therefor more space.
 
<img width="1021" alt="Bildschirm­foto 2023-03-30 um 14 09 40" src="https://user-images.githubusercontent.com/51958720/228831508-1f3c31dd-7f1c-4ef8-864a-7aed4185f032.png">
