### ISSUE TITLE
[Feature request]: Single Width Ligature Glyphs

### ISSUE THREAD

**Issue by 23TNC** [MonoLisaFont/feedback#201]
### What feature are you proposing?

When I type the cursor will advance, even if there is a replacement.

Here we have a screenshot from kitty where the glyphs are miss aligned
![Screenshot from 2023-03-17 21-39-07](https://user-images.githubusercontent.com/20226280/226079390-f3e5c307-c267-4278-8a57-2a811733d699.png)

Here we have a screenshot from a text editor where the glyphs are aligned properly
![Screenshot from 2023-03-17 21-40-00](https://user-images.githubusercontent.com/20226280/226079437-bbc02b3b-6fda-488f-b18c-a46ebad665bf.png)

Here we have the text in another font
![Screenshot from 2023-03-17 21-40-27](https://user-images.githubusercontent.com/20226280/226079456-c09c711c-afc0-4ed2-a89c-4f5dfc0ddb7f.png)

Kitty will make the correct substitutions, but retain the additional character width.  I have not yet identified how to solve this.

Thank you for your time.

**Comment by bebraw** [comment]
Can you report this issue to kitty as it's related to using a backup font for the missing glyphs? What might happen is that their rendering gets confused because of differing glyph widths in the fonts but that's only a guess.

I would also check what happens in other terminals like iTerm 2 to see if the issue is specific to kitty.

Note that glyph rendering order changed in 2.005 so that might make a difference as well but it's hard to tell as you didn't report the version.
