### ISSUE TITLE
[Bug]: Font symbols not rendered in Windows Terminal

### ISSUE THREAD

**Issue by jtourlamain** [MonoLisaFont/feedback#223]
### Edition

Basic (Personal)

### What version are you using?

2.008

### What type of weights are you using?

Static (customized)

### Operating system

Windows 11

### Program

Windows Terminal

### Display resolution

2560x1440

### What happened?

The Setup:
I use the "Windows Terminal" and powershell with oh-my-posh.
The theme that I'm using with oh-my-posh for my prompt is markduiker:
https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/marcduiker.omp.json

The Problem:
The symbols in the prompt seem to be missing. 
When using another font (ex. patched nerd-font), the symbols are displayed correctly in "Windows Terminal".

In Wezterm however the prompt is displayed correctly with the MonoLisa font. 

Expected:
I would expect that the symbols are rendered correctly in "Windows Terminal".

**Comment by bebraw** [comment]
Check https://www.monolisa.dev/faq#how-to-enable-nerd-fonts-with-monolisa . Applying Nerd Fonts like discussed there might solve it for you.

**Comment by jtourlamain** [comment]
As wezterm shows the symbols (like \ue0b4) correctly, I suppose it should work on Windows Terminal as well. That is the reason why I didn't patch the font

**Comment by bebraw** [comment]
It looks like https://www.compart.com/en/unicode/U+E0B4 is from Private Use Area which implies it's coming from something like Nerd Fonts and therefore it hasn't been implemented.

One option is that wezterm is doing something different for the characters it doesn't find. In some platforms it's possible to set up Nerd Fonts using a fallback font so that it looks up anything missing from another font.

I would try patching as we are not going to implement Nerd Fonts (it's over thousand characters to reimplement).

**Comment by jtourlamain** [comment]
Ok, thx, sorry for the confusion. I'll patch the font.
