### ISSUE TITLE
Font Downloader Won’t Allow Choice of OpenType Features

### ISSUE THREAD

**Issue by carlomunguia** [MonoLisaFont/feedback#235]
### Edition

Plus

### What version are you using?

2.010

### What type of weights are you using?

Static (customized)

### Operating system

MacOS

### Program

Safari 

### What happened?

Try to choose custom features for a custom download on the My Orders page: 

- The feature you select will no longer stick ie if you choose Alt curly brackets and then move to select Alt @ sign, your choice for Alt curly brackets will disappear
-  This happens on both Desktop & Mobile

This is a major issue, should be addressed immediately so people can download custom versions of 2.011

**Comment by bebraw** [comment]
I have trouble reproducing this. Which browser are you using?

**Comment by bebraw** [comment]
Ah, Safari. I'll try there.

**Comment by bebraw** [comment]
I cannot reproduce the behavior in Safari either. I wonder if it's a specific version.

**Comment by carlomunguia** [comment]
I'm so sorry, it's actually Chrome on Desktop (most current update) , Safari for macOS (13.6 Ventura) & Safari for mobile (iOS 16.6).  Just recreated issue in all environments. @bebraw

**Comment by bebraw** [comment]
Ok, I logged in using your account on Chrome 118.0.5993.88 on desktop. I chose Alt curly bracket first and Alt at after that and the selection was sticking as expected.

Let's see if someone else can reproduce this as without a local reproduction it's tough to fix.

**Comment by carlomunguia** [comment]
Yeah I have no idea what's going on.  Even on a different Windows laptop I'm recreating it with Chrome (latest) after I login with my Plus receipt #.

**Comment by bebraw** [comment]
Out of curiosity, I tested this on Safari using my iPhone with your account and the selection stuck as below:

![763590AE-BDD1-4344-AC44-BBD04AE91A9D_1_101_o](https://github.com/MonoLisaFont/feedback/assets/166921/b6a67f94-80b6-461e-8d82-82ae3d3a53f8)

I tried logging in with and without # and it worked the same. I know # gets stripped so it shouldn't make a difference.

Technically we could try to serialize the selection to the address bar to make it more robust but it would be better to find the root issue instead of trying to fix blindly. Let's see if the developer can reproduce this.

**Comment by carlomunguia** [comment]
So wait, it's not sticking on _multiples_ ie choosing one selection & then moving to another. The original selection will disappear. I wonder what's going on here.  Let me know if developer confirms it - right now I can't download a custom version of 2.011 on any of my devices (which is so strange)

**Comment by bebraw** [comment]
> So wait, it's not sticking on multiples ie choosing one selection & then moving to another. The original selection will disappear. I wonder what's going on here. Let me know if developer confirms it - right now I can't download a custom version of 2.011 on any of my devices (which is so strange)

That's how it works by definition since the customize tool is **freezing** the functionality directly to the font. In other words it replaces the original glyphs with the ones selected so you can use the features in environments that don't support opentype features. Therefore it makes sense to select specifically only alternative brackets.

Editors like VS Code are an exception to this rule as [covered in the FAQ](https://www.monolisa.dev/faq#what-are-the-suggested-settings) since you can adjust the features through their settings.

**Comment by okonet** [comment]
I cannot reproduce this either. I just tried to download a custom version of the font and it all worked as expected:

<img width="955" alt="CleanShot 2023-10-20 at 14 17 58@2x" src="https://github.com/MonoLisaFont/feedback/assets/11071/bb3985b2-3d0e-4986-94a6-be3ade908942">

**Comment by okonet** [comment]
Looking at your screenshot it seems okay too. The selection is indicated by the accent color, not the border (which is used to indicate the focused element). Maybe that's what caused the confusion?

In this case, I could improve the styling of the radio group control.

**Comment by carlomunguia** [comment]
As of this morning, I still cannot select multiple selections for the download on iOS 16.6 (Safari), Chrome (newest) on Windows, Chrome (newest) on macOS 13.6 Ventura & Safari on macOS 13.6 Ventura.

Could something be wrong with my account? 
How is this happening across multiple devices & browsers but not your team? 

Seriously confused, currently using workaround with settings.json in VSCode (setting stylistic sets) but it's really not ideal.

**Comment by carlomunguia** [comment]
As of this morning, behavior returned to normal. 

Yesterday all devices were not working (Chrome on Windows & MacOS, Safari on iOS & macOS)

What could of been the issue?

Welcome to close this issue as resolved but could stay open to possibly refactor the design? 

Thanks again!
