### ISSUE TITLE
[Bug]: Lowercase é and è are not symmetric

### ISSUE THREAD

**Issue by ghost** [MonoLisaFont/feedback#239]
### Edition

Basic (Personal)

### What version are you using?

2.011

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS Sonoma 14.1

### What happened?

Hello,

It bothers me that MonoLisa’s lowercase é and è are not symmetric. This is particularly blatant when the 2 characters are found in proximity to each other, inside the same word, which happens relatively often in the French language:

élève
préfères
étagère
phénomène
…

Note that the uppercase É and È are fine.

(See simple screenshot taken in TextEdit.)

![not_symmetric](https://github.com/MonoLisaFont/feedback/assets/146453846/08b2a6b5-ef7a-4e52-b1a3-2ec4d4a38327)

**Comment by okonet** [comment]
Thanks for the report! We will take a look at it soon.

**Comment by okonet** [comment]
Hmm, it looks correct in the specimen. ![image](https://github.com/MonoLisaFont/feedback/assets/11071/8c844544-2bc5-463d-8d55-ef36ca56ce9d)

**Comment by ghost** [comment]
On my computer, the specimen on the website looks incorrect. And I tried different browsers.

(See 2 simple screenshots taken in Safari.)

![not_symmetric2](https://github.com/MonoLisaFont/feedback/assets/146453846/6cce4cd7-baff-470f-9b1e-9f406a0993b2)
![not_symmetric3](https://github.com/MonoLisaFont/feedback/assets/146453846/1e5437fc-9ed2-476c-b62f-52850182f186)

**Comment by ghost** [comment]
OK, I played around with the specimen. If I specify using the browser inspector:

`-webkit-font-smoothing: antialiased;`

the è looks correct. But the other values, such as:

`-webkit-font-smoothing: auto;`

or:

`-webkit-font-smoothing: subpixel-antialiased;`

look incorrect.

And “auto” is the default value.

(See 2 additional screenshots.)

![not_symmetric4](https://github.com/MonoLisaFont/feedback/assets/146453846/b50a26e6-03d0-4489-874f-8f22b15cd43f)
![not_symmetric5](https://github.com/MonoLisaFont/feedback/assets/146453846/c73c2881-98db-4210-8a10-b98d501b6bbc)

**Comment by MarcusSterz** [comment]
That’s weird. As I suspected, it is not just the `e` but the accent. If we look at the diacritics of `i` we see the same effect. Still everything looks fine on two browsers on my screen as well. Will look into the file today.

**Comment by MarcusSterz** [comment]
So the bespoken accent (‘grave’) looks flawless in the Glyphs file (pic below). The source file as well as static or variable TTFs look perfect. Also the `grave` is only a mirrored component from the `acute` accent. The problem is likely somewhere else. 

<img width="979" alt="Bildschirmfoto 2023-11-02 um 12 14 18" src="https://github.com/MonoLisaFont/feedback/assets/51958720/51a11cc1-57b0-48ae-85c3-4b618d6ec869">

However: There is an definitely issue with the rendering of the `grave`: I see it also in TextEdit, TextMate, Apples Fontbook and FontExplorer (pic shows Apple Fontbook)
<img width="777" alt="Bildschirmfoto 2023-11-02 um 12 23 57" src="https://github.com/MonoLisaFont/feedback/assets/51958720/67667f9f-bec1-439f-b4e5-2a996200b9e4">

I do not see it in Indesign, though (pic with blue letters) or Affinity Publisher.

<img width="1064" alt="Bildschirmfoto 2023-11-02 um 12 54 47" src="https://github.com/MonoLisaFont/feedback/assets/51958720/4cfda47c-a8b9-4035-8c83-a448cbe683bb">

Edit: Adding that this issue does not appear with 2.010. Also I have not touched the accents for 2.011. This is an interesting problem for the Glyphs Forum ;-)

**Comment by MarcusSterz** [comment]
Will be solved in the upcoming version.

**Comment by bebraw** [comment]
If you want to try, the upcoming fix is available in the prerelease version now.

**Comment by ghost** [comment]
Apparently, the preview release channel isn’t available for Basic users like me. But I will take your word for it, and close this issue.

**Comment by bebraw** [comment]
Fixed in 2.012 available now.

**Comment by ghost** [comment]
Indeed, problem fixed in the new version. Thank you very much!

![Capture d’écran](https://github.com/MonoLisaFont/feedback/assets/146453846/8658651f-1202-4157-ae27-a7cd35495eb5)
