### ISSUE TITLE
[Feature request]: Add another font ligature variation for double underscores symbol

### ISSUE THREAD

**Issue by ronaldpaek** [MonoLisaFont/feedback#249]
### What feature are you proposing?

What feature are you proposing?

I been using your font for almost 2 years now, I love the font and i'm happy to see new font variations being added, here is just a suggestion.

I am wondering if we could have another variation for the double under score symbol __ to be connected together as a solid line? and maybe another proposal to for the double under score symbol __( and the opening curly braces to be fused together with no spaces as well?

![CleanShot 2024-01-11 at 03 03 53@2x](https://github.com/MonoLisaFont/feedback/assets/95109313/e4408190-8710-463d-9922-fd17cd3341be)

**Comment by okonet** [comment]
Hey! Thanks for your feedback and being a customer for so long!

Frankly, I think it will make things less legible since you won't be able to tell how many underscores there are. Wouldn't you agree?

Also connecting `_(`: we had similar ligatures in the past, but unfortunately they would break most editors syntax highlighting so we decided to get rid of them. 

Hope that makes sense.

**Comment by ronaldpaek** [comment]
Yes that makes sense I figured from a legibility standpoint it would make
it harder to read, but I seen recent updates with different variations so I
thought I would ask. 🙂

**Comment by bebraw** [comment]
We decided not to proceed with the feature. Thank you for the suggestion, however.
