### ISSUE TITLE
[Bug]: Confusing download page

### ISSUE THREAD

**Issue by rockmandash** [MonoLisaFont/feedback#291]
### Edition

Plus

### What version are you using?

2.015

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS 15.1.1

### Program

Visual Studio Code 1.95.3

### What happened?

The download page is quite confusing. There doesn’t seem to be a clear distinction between downloading the custom font and the regular font. If I want to download the regular version, should I avoid selecting any OpenType features? I’m not sure.

Additionally, it looks like only TTF files are available for the Plus plan—there’s no OTF version, correct? I couldn’t find answers to these questions in the FAQ. Does this mean the regular font is provided as a TTF file too?

**Comment by bebraw** [comment]
For VS Code, it's best to download a non-customized version (i.e., avoid selecting any OpenType features since they'll be included by default instead of frozen). Here are sample settings: https://www.monolisa.dev/faq#what-are-the-suggested-settings-for-visual-studio-code .

Only TTF is included as that works well regardless of the platform. No OTF exists.
