### ISSUE TITLE
Adding nerd-fonts

### ISSUE THREAD

**Issue by chmanie** [MonoLisaFont/feedback#73]
I was wondering whether anyone has managed to inject the nerd-fonts (https://github.com/ryanoasis/nerd-fonts) glyphs into this font. I tried but with no luck. 

These two glyphs for example are not displayed properly: , 

**Comment by bebraw** [comment]
It wouldn't be possible for us to include nerd-fonts to the typeface due to licensing reasons. We cannot support the use case officially but at the same time we cannot prohibit you from patching the font. 😄

**Comment by jaredramirez** [comment]
Some terminals use a fallback system if you don't have a Nerd font. Rather than patching you can:
1. Download just the Nerd symbols [here](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf)
2. Set` MonoLisa` as your default font on your terminal emulator
3. Set `Symbols Nerd Font` as the fallback font

When the terminal renders it will try to find the MonoLisa symbols first, then if it fails (like it will for Nerd fonts), it will try the fallback font. This works for me on [Wezterm](https://wezfurlong.org/wezterm/) and I believe it works for [Konsole](https://konsole.kde.org/) as well. It may not work for everything, but might be easier than patching!

**Comment by chmanie** [comment]
I actually accomplished the patch in the end. The trick is to use the `--mono` option when [patching](https://github.com/ryanoasis/nerd-fonts#option-8-patch-your-own-font)
