### ISSUE TITLE
Terminals of italic "f" 

### ISSUE THREAD

**Issue by okonet** [MonoLisaFont/feedback#8]
The bottom terminal of the italic `f` is long and it looks weird in combination with `i` which is a very common keyword (`if`):
 
![CleanShot 2020-03-11 at 15 33 00](https://user-images.githubusercontent.com/11071/76428239-b11a3c00-63ad-11ea-901d-3546c63d33a0.png)

I really like how it looks in case of `fi` since (I think) it's being cut by the editor a bit.

Can we tune the terminal of `f` to be a bit subtle?

**Comment by bebraw** [comment]
I have a related report from a user. Screenshot below to illustrate:

![image](https://user-images.githubusercontent.com/166921/100463282-3d9f9280-30d4-11eb-9e8d-368c643cf14a.png)

Quote: "...at the top of my head I can only think of that I'm not really a fan of the italic f which I think is a little bit big compared to the rest and usually comes in the way of the previous character as shown below"

**Comment by msallent** [comment]
Quote and screenshot above are mine.

I do agree that a change here would be nice. I often found myself trying to rename variables as to not include the letter f because depending on the word, it looked weird compared to the other characters.

IMO, I feel it's a bit too tall and that's why it stands out so much.
